Added modal
js-tasks-ru/htmlcss-20210916_ea-husainova pull request #11
Opened 2021-09-29 09:58 UTC by Elya-Husainova

2021-09-29 09:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-29 11:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-29 17:22 UTC, GSemikozov requested changes

2021-09-29 17:22 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button_open-modal {
стиль кнопки полностью соответствует тому что у нас называется .button_primary - не стоит здесь отдельно описывать одни и те же стили )

2021-09-29 17:22 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
критически важно через fixed - чтобы привязываться именно к окну браузера

2021-09-29 17:22 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__block {
можно удалить этот враппер если .block__content спозиционируем абсолютно

2021-09-29 17:22 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> + .content__button_close {
можно просто как __button, не обязательно использовать модификатор (чтобы что-то модифицировать, сначала это что-то надо описать))

2021-10-01 08:25 UTC, Elya-Husainova commented on 05-lection3/02-modal/modal.css
> +.button_open-modal {
✓. Подключила button.css

2021-10-01 08:34 UTC, Elya-Husainova commented on 05-lection3/02-modal/modal.css
> + .content__button_close {
✓. Удалила модификатор close

2021-10-01 08:35 UTC, Elya-Husainova commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
✓. Задала position: fixed для .modal

2021-10-01 08:58 UTC, Elya-Husainova commented on 05-lection3/02-modal/modal.css
> +.modal__block {
✓. Враппер удалила, спозиционировала абсолютно

2021-10-01 10:40 UTC, GSemikozov requested changes

2021-10-01 10:40 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button_open-modal {
и удалить отсюда еще надо)

2021-10-01 10:40 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: relative;
вот здесь лучше тоже. absolute,  и тогда не придется ниже делать страшные -200px  ;)

2021-10-02 08:17 UTC, Elya-Husainova commented on 05-lection3/02-modal/modal.css
> +.button_open-modal {
✓ удалила из css дублирующее правило

2021-10-02 08:20 UTC, Elya-Husainova commented on 05-lection3/02-modal/modal.css
> +    position: relative;
✓ сделала абсолютное позиционирование с отступами сверху-справа

2021-10-03 17:15 UTC, GSemikozov approved these changes

2021-10-03 17:15 UTC, merged