Added component's page
js-tasks-ru/htmlcss-20210916_ea-husainova pull request #13
Opened 2021-10-02 08:14 UTC by Elya-Husainova

2021-10-02 08:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-02 08:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-10-02 08:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-10-02 16:56 UTC, GSemikozov requested changes

2021-10-02 16:56 UTC, GSemikozov commented on pages/template.css
> +.nav__item {
описываем как отдельный блок, поэтому - лучше сразу оформить как отдельный компонент

2021-10-03 07:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-03 07:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-10-03 07:46 UTC, Elya-Husainova commented on pages/template.css
> +.nav__item {
✓.  создала компонент nav, nav.css  в папке components

2021-10-03 17:14 UTC, GSemikozov approved these changes

2021-10-03 17:14 UTC, merged