Added background-image
js-tasks-ru/htmlcss-20210916_ea-husainova pull request #14
Opened 2021-10-03 08:45 UTC by Elya-Husainova

2021-10-03 08:45 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-03 17:18 UTC, GSemikozov requested changes

2021-10-03 17:18 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media (max-width: 400px) {
это медиа-запрос лишний, тут мы просто определяем что покажем на мобилке

2021-10-03 17:18 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media (min-width: 400px) and (max-width: 768px) {
а вот дальше - идем наверх, при этом указывать ` and (max-width:` не обязательно - мы двигаемся по точкам наверх через min-width

2021-10-05 12:43 UTC, Elya-Husainova commented on 06-lection4/02-background-image/background-image.css
> +@media (max-width: 400px) {
✓ удалила медиа-запрос

2021-10-05 12:43 UTC, Elya-Husainova commented on 06-lection4/02-background-image/background-image.css
> +@media (min-width: 400px) and (max-width: 768px) {
✓ оставила только min-width

2021-10-05 14:48 UTC, GSemikozov approved these changes

2021-10-05 14:48 UTC, merged