Added icons for components
js-tasks-ru/htmlcss-20210916_ea-husainova pull request #17
Opened 2021-10-04 09:38 UTC by Elya-Husainova

2021-10-04 09:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-04 16:19 UTC, GSemikozov requested changes

2021-10-04 16:19 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <svg display="none">
тут такая история... чтобы вот это вот все не описывать в каждом отдельном компоненте (иначе суть спрайта  / переиспользуемых иконок теряется) - нужно собрать единый спрайт в одном файле и подключать уже его. Его можно положить в assets/icons

2021-10-05 13:15 UTC, Elya-Husainova commented on 03-lection1/02-accordion/index.html
> +        <svg display="none">
✓. сделала отдельный svg-файл

2021-10-05 14:48 UTC, GSemikozov approved these changes

2021-10-05 14:48 UTC, merged