add solution for sceleton
js-tasks-ru/htmlcss-20210916_ea-husainova pull request #7
Opened 2021-09-25 09:23 UTC by Elya-Husainova

2021-09-25 09:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-26 13:04 UTC, GSemikozov requested changes

2021-09-26 13:04 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.card {
так-с, тут у нас верстка совсем не по БЭМ, так что - будем разбираться )
1. почему в блоке skeleton у нас card? корневой класс данного блока -  это .skeleton
2. далее, у скелетона есть универсальный элемент - skeleton__line (или skeleton__placeholder, как будет. угодно), который может быть разной ширины, ширину будем контролировать через модификаторы (саму ширину задаем в процентах) - .skeleton__line_sm, .skeleton__line_md, .skeleton__line_lg
3. есть еще один элемент - кружочек, его можно оформить через модификатор line (поскольку это по сути тот же line, с серым фоном, но - круглый) - .skeleton__line_avatar { стили }, либо как отдельный элемент - .skeleton__avatar
4. все элементы пишутся через 2 нижних подчеркивания, через 1 - модификаторы. Поэтому - sceleton_title ->  sceleton__title, sceleton_body -> sceleton__body, info_placeholder -> skeleton__info

2021-09-27 12:21 UTC, Elya-Husainova commented on 04-lection2/02-skeleton/skeleton.css
> +.card {
✓. Поправила все по пунктам замечаний

2021-09-27 15:13 UTC, GSemikozov approved these changes

2021-09-27 15:13 UTC, merged